### ISSUE TITLE
Создание wiki

### ISSUE THREAD

**Issue by rorosin** [SoKnight/EasyDonateSDK#1]
Уважаемый SoKnight, прошу создать wiki на github или gitbook, для того, чтобы были понятны все функции вашего sdk.

**Comment by SoKnight** [comment]
> Уважаемый SoKnight, прошу создать wiki на github или gitbook, для того, чтобы были понятны все функции вашего sdk.

Да, я хотел заняться этим сразу после релиза SDK, но пока не получается.
Если появится свободное время - обязательно займусь этим. За первую звёздочку спасибо ❤

**Comment by rorosin** [comment]
Также могу предложить свою помощь в этом вопросе.

**Comment by SoKnight** [comment]
> Также могу предложить свою помощь в этом вопросе.

Вики уже закончена :D
